### ISSUE TITLE
Replace Google search with DuckDuckGo search

### ISSUE THREAD

**Issue by ksbhaskar** [YottaDB/YottaDBdoc#81]
https://api.duckduckgo.com/api defines a DuckDuckGo search API. Since DuckDuckGo does not track users, it would be more in keeping with YottaDB's ethos to use the DuckDuckGo API for the search tool rather than the Google tool.

**Comment by ranjani789** [comment]
We can do this, as long as it's okay that search results do not open on our web pages ( Here's what DuckDuckGo says about it: "Because of the way we generate our search results, we do not have the syndication rights to allow you to host our results on your site (e.g. in a frame). When your users click on the results they will be instead taken to our site." )

Is that acceptable?

**Comment by ksbhaskar** [comment]
It seems reasonable, but I'd like to try it in a sandbox, and then decide.

**Comment by ranjani789** [comment]
DuckDuckGo Search box replaces the Google Search box on all documentation pages. #82
